#!/bin/sh
# postrm script for APPLICATION_PACKAGE
#
# Override du template jpackage par défaut : retire le lien de la commande "lecture" créé par
# postinst dans /usr/local/bin (vers /opt/teacherflow/bin/lecture-fast, lui-même supprimé avec
# le reste de /opt/teacherflow par dpkg, pas besoin de le retirer ici). Seulement sur suppression
# complète (remove/purge), pas sur upgrade : le postinst du nouveau paquet recréera le lien juste
# après.
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    purge|remove)
rm -f /usr/local/bin/lecture
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
